image:
  repository: sammielas/gitopspro
  tag: e318643
  pullPolicy: IfNotPresent
service:
  type: NodePort
  port: 8085
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false